from fyers_api.websocket import ws
client_id='F4ZJFEICWT-100'
access_token_valid = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJhcGkuZnllcnMuaW4iLCJpYXQiOjE2NDM3NzU5MDgsImV4cCI6MTY0Mzg0ODIwOCwibmJmIjoxNjQzNzc1OTA4LCJhdWQiOlsieDowIiwieDoxIiwieDoyIiwiZDoxIiwiZDoyIiwieDoxIiwieDowIl0sInN1YiI6ImFjY2Vzc190b2tlbiIsImF0X2hhc2giOiJnQUFBQUFCaC1nZWtmd1NXZzFBbmVMSTZtcGJRdzA4Y0t2eFNUUHdIbXJpQnRnVDVJSmJvTmRkQ0Q3UnB6VmtMbHdkbVFldGl6Sm5LSEJVZlRJcVNUd01ZalVWTzVlYjRzd2xobHk3djVEbmZKV3JySkJFYTRyQT0iLCJkaXNwbGF5X25hbWUiOiJHQVpJIFNIQU1TSEVSIEFITUFEIiwiZnlfaWQiOiJERzAwMzM5IiwiYXBwVHlwZSI6MTAwLCJwb2FfZmxhZyI6IlkifQ.9qJmlK9tUyG_332SUJjroPD-xHS12wqN1NStSqb6L8E'
access_token = client_id+":"+access_token_valid
data_type = 'symbolData'
symbol = ['NSE:TATAMOTORS-EQ','NSE:ITC-EQ']
def custom_message(ticks):
    print(ticks.response)

ws.FyersSocket.websocket_data = custom_message
fs = ws.FyersSocket(access_token, data_type,symbol)
fs.subscribe()